AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda@Edge function for Presence

Resources:
  EdgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: presence_edge.app.handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 30
      AutoPublishAlias: live
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: 'sts:AssumeRole'

Outputs:
  EdgeFunctionVersion:
    Description: Lambda@Edge versioned ARN for CloudFront association
    Value: !Ref EdgeFunction.Version
  EdgeFunctionArn:
    Description: Lambda@Edge function ARN
    Value: !GetAtt EdgeFunction.Arn
