version: "0.5"

processes:
  0-healthcheck:
    command: ./scripts/dev-healthcheck-start.sh
  1-auth:
    command: ./scripts/dev-auth-start.sh
  1-sam:
    command: ./scripts/dev-sam-start.sh
  1-web:
    command: ./scripts/dev-web-start.sh
  2-proxy:
    command: ./scripts/dev-proxy-start.sh