"""Human-readable ID generator.

Format: adjective-adjective-noun
All words are common English and 6 characters or fewer.
"""

from __future__ import annotations

import random


ADJECTIVES = [
	"able", "above", "absent", "acute", "adept", "afire", "afraid", "after", "agile", "ajar",
	"alert", "alien", "alike", "alive", "alone", "aloof", "amber", "ample", "amused", "angry",
	"antsy", "any", "apt", "arch", "ardent", "arid", "armed", "artsy", "ashen", "asleep",
	"atomic", "attic", "avid", "awake", "aware", "awful", "azure", "back", "bad", "baked",
	"bald", "bare", "based", "basic", "batch", "beady", "beige", "bent", "best", "bias",
	"big", "bitter", "black", "blade", "blamed", "bland", "blank", "blare", "bleak", "bleed",
	"blend", "blind", "bliss", "block", "blond", "blood", "bloom", "blown", "blue", "blunt",
	"blur", "blurry", "blush", "board", "boast", "bogus", "bold", "bonny", "boozy", "bored",
	"boring", "born", "boss", "both", "bound", "boxed", "brave", "bravo", "brazen", "brief",
	"bright", "briny", "brisk", "broad", "broke", "brown", "brute", "built", "bulky", "bumpy",
	"busy", "calm", "campy", "canine", "canny", "catty", "chaste", "cheap", "chief", "chill",
	"choice", "chubby", "civic", "civil", "clad", "clean", "clear", "cliff", "close", "cloudy",
	"clumsy", "coarse", "cocky", "cold", "comic", "common", "cool", "coral", "corny", "cosy",
	"cozy", "crafty", "craggy", "crisp", "cross", "cruel", "cubic", "curly", "curved", "cute",
	"daft", "daily", "dainty", "damp", "dapper", "dark", "dazed", "dead", "deaf", "dear",
	"deep", "dense", "dented", "dew", "dim", "dingy", "dire", "dirty", "dizzy", "done",
	"dopey", "doting", "double", "drab", "dreamy", "dreary", "drift", "droop", "droopy", "drunk",
	"dry", "dual", "dull", "dumb", "dusty", "dyed", "dying", "eager", "early", "earthy",
	"easy", "edgy", "eerie", "eight", "elite", "empty", "entire", "epic", "equal", "even",
	"every", "evil", "exact", "extra", "faded", "faint", "fair", "fake", "false", "famed",
	"fancy", "far", "fast", "fatal", "fated", "fatty", "fazed", "few", "fickle", "fierce",
	"fiery", "fifth", "fine", "firm", "first", "fishy", "five", "fixed", "fizzy", "flabby",
	"fleet", "floppy", "fluffy", "fluid", "flying", "foggy", "fond", "formal", "forth", "found",
	"four", "frank", "frayed", "free", "fresh", "frizzy", "front", "frosty", "frothy", "frozen",
	"full", "funky", "funny", "furry", "fused", "fussy", "future", "fuzzy", "gamy", "gaudy",
	"gaunt", "gentle", "giddy", "giant", "gimpy", "given", "giving", "glad", "glib", "glum",
	"gnarly", "gold", "golden", "gone", "good", "gooey", "goofy", "grand", "grave", "gray",
	"great", "greedy", "green", "grimy", "grim", "gruff", "guilty", "gummy", "gusty", "hairy",
	"happy", "hard", "hardy", "harsh", "hasty", "hazy", "heady", "hearty", "heated", "heavy",
	"hefty", "high", "hip", "hoarse", "hollow", "homely", "honest", "hot", "huge", "hulled",
	"humble", "hungry", "hurt", "husky", "hushed", "icy", "ideal", "idle", "ill", "inane",
	"inner", "irate", "itchy", "jam", "jazzy", "joint", "jolly", "jovial", "jumbo", "jumpy",
	"junior", "just", "keen", "khaki", "kind", "kingly", "knotty", "known", "lame", "lanky",
	"large", "last", "late", "later", "latin", "lavish", "lawful", "lazy", "leafy", "lean",
	"leery", "left", "legal", "level", "light", "likely", "limp", "lined", "lit", "live",
	"lively", "livid", "lofty", "lone", "lonely", "long", "loopy", "loose", "lost", "loud",
	"loved", "lovely", "loving", "low", "lower", "lowly", "loyal", "lucky", "lumpy", "lunar",
	"lush", "mad", "magic", "main", "major", "male", "many", "marked", "mass", "matt",
	"meager", "mean", "meaty", "meek", "mellow", "mental", "merry", "messy", "mild", "milky",
	"minor", "minty", "mint", "misty", "mixed", "moist", "moldy", "moral", "mossy", "MotH",
	"mousy", "moved", "moving", "much", "muddy", "muggy", "mural", "murky", "mushy", "musty",
	"mute", "muted", "naive", "naked", "nappy", "narrow", "nasty", "natty", "naval", "near",
	"neat", "needy", "nervy", "new", "newsy", "next", "nice", "nifty", "nine", "ninth",
	"noble", "noisy", "north", "noted", "novel", "numbed", "nutty", "oaken", "obese", "odd",
	"oily", "ok", "old", "older", "one", "only", "open", "optic", "other", "outer",
	"oval", "over", "owing", "own", "pagan", "paid", "pale", "party", "past", "pasty",
	"pearly", "perky", "pesky", "petite", "petty", "phony", "piano", "picks", "picky", "pink",
	"plain", "plumb", "plump", "plush", "poetic", "pointy", "poised", "polar", "polite", "poor",
	"potent", "posh", "pretty", "pricey", "prim", "prime", "prior", "privy", "prize", "prized",
	"prompt", "proof", "proper", "proven", "proud", "public", "puffy", "pulpy", "pumped", "punchy",
	"pure", "pushy", "putrid", "quaint", "queen", "queasy", "quick", "quiet", "quirky", "rabid",
	"racing", "rainy", "random", "rapid", "rare", "rash", "ratty", "raw", "ready", "real",
	"rear", "recent", "red", "regal", "remote", "repent", "ribbed", "rich", "right", "rigid",
	"ripe", "risen", "risky", "ritual", "roast", "rocky", "rogue", "roomy", "rosy", "rotten",
	"rough", "round", "royal", "ruddy", "rude", "rugby", "rugged", "rum", "rural", "rushy",
	"russet", "rustic", "rusty", "rutted", "sad", "safe", "salty", "same", "sandy", "sane",
	"sassy", "sawing", "scaly", "scarce", "scared", "scary", "scorny", "seamy", "second", "secret",
	"self", "serene", "set", "seven", "severe", "shabby", "shady", "shaggy", "shaken", "shaky",
	"shamed", "sharp", "sheer", "shiny", "short", "showy", "shrewd", "shrill", "shut", "shy",
	"sickly", "sided", "silent", "silky", "silly", "silver", "simple", "single", "six", "sixth",
	"sixty", "sized", "sketchy", "skinny", "slack", "sleek", "sleepy", "slick", "slight", "slim",
	"slimy", "sloped", "sloppy", "slow", "sly", "small", "smart", "smelly", "smooth", "snappy",
	"snazzy", "snippy", "snowy", "snug", "sober", "social", "soft", "soggy", "soiled", "solid",
	"solo", "some", "sonic", "sooty", "sore", "sorry", "sought", "sound", "soupy", "sour",
	"south", "sown", "spare", "spicy", "spiffy", "spiky", "spiral", "splay", "split", "spoken",
	"spongy", "spooky", "sporty", "spotty", "spring", "square", "squint", "stable", "staid", "stale",
	"stark", "state", "static", "steady", "steel", "steep", "sterile", "stern", "sticky", "stiff",
	"still", "stingy", "stocky", "stoic", "stony", "stormy", "stout", "strict", "strong", "stuck",
	"study", "stuffy", "stupid", "sturdy", "suave", "subtile", "sudden", "sullen", "sultry", "summer",
	"sundry", "sunny", "super", "supple", "svelte", "swank", "swanky", "sweet", "swift", "sworn",
	"tabby", "taboo", "tacit", "tacky", "taken", "tal", "talkly", "tall", "tame", "tan",
	"tangy", "taped", "tardy", "tart", "tasty", "taut", "tawny", "teal", "teensy", "tense",
	"tenth", "tepid", "terse", "tested", "testy", "thick", "thin", "third", "thirsty", "thorny",
	"tidy", "tight", "timely", "timid", "tiny", "tinted", "tired", "titled", "token", "torn",
	"total", "totem", "tough", "tragic", "tribal", "tricky", "trifle", "trim", "trite", "true",
	"trying", "tubby", "tuned", "turbid", "twin", "two", "ugly", "ultra", "unable", "unborn",
	"uncut", "under", "undue", "uneven", "unfair", "unfit", "union", "unit", "united", "unity",
	"unjust", "unkind", "unknow", "unlit", "unmet", "unread", "unripe", "unsafe", "unsaid", "unseen",
	"unsold", "unsure", "untidy", "untold", "untrue", "unused", "unwary", "unwell", "unworn", "upbeat",
	"upset", "upward", "urban", "usable", "used", "useful", "useless", "utmost", "vacant", "vague",
	"vain", "valid", "valued", "vapid", "varied", "vast", "veiled", "velvet", "verbal", "vertex",
	"vexed", "viable", "violet", "viral", "virgin", "visual", "vital", "vivid", "vocal", "void",
	"warm", "warped", "wary", "waste", "watery", "wavy", "wavy", "waxy", "weak", "weary",
	"weekly", "weepy", "weird", "west", "wet", "whole", "wicked", "wide", "wild", "wiley",
	"wily", "windy", "wintry", "wired", "wiry", "wise", "wispy", "witty", "wooden", "wooded",
	"woozy", "wordy", "worldly", "worn", "worthy", "woven", "wrong", "young", "yummy", "zany",
	"zesty", "zippy", "zonal",
]


NOUNS = [
	"acorn",
	"actor",
	"angel",
	"apple",
	"arrow",
	"award",
	"badge",
	"baker",
	"beach",
	"beard",
	"beast",
	"bench",
	"berry",
	"bison",
	"blade",
	"board",
	"bonus",
	"boot",
	"brain",
	"brick",
	"broom",
	"bunny",
	"cable",
	"cabin",
	"candy",
	"cargo",
	"charm",
	"chess",
	"chime",
	"choir",
	"cider",
	"cliff",
	"clock",
	"cloud",
	"coast",
	"comet",
	"coral",
	"corn",
	"couch",
	"court",
	"crane",
	"cream",
	"creek",
	"crown",
	"daisy",
	"dance",
	"delta",
	"diner",
	"dough",
	"dream",
	"drift",
	"drum",
	"eagle",
	"earth",
	"ember",
	"event",
	"fairy",
	"field",
	"flame",
	"flint",
	"flora",
	"forge",
	"fox",
	"frame",
	"fruit",
	"globe",
	"grace",
	"grain",
	"graph",
	"grove",
	"guest",
	"guide",
	"habit",
	"harbor",
	"heart",
	"honey",
	"horse",
	"house",
	"index",
	"island",
	"ivory",
	"jelly",
	"judge",
	"kite",
	"laser",
	"leaf",
	"lemon",
	"linen",
	"lodge",
	"maple",
	"mason",
	"medal",
	"melon",
	"merit",
	"model",
	"money",
	"moon",
	"music",
	"ocean",
	"olive",
]


def generate_human_id() -> str:
	"""Generate a human-readable ID in adjective-adjective-noun format."""

	adj1 = random.choice(ADJECTIVES)
	adj2 = random.choice(ADJECTIVES)
	noun = random.choice(NOUNS)
	return f"{adj1}-{adj2}-{noun}"

