AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Serverless v3 PostgreSQL database cluster

Parameters:
  TenantId:
    Type: String
    Default: main

  ParamName:
    Type: String
    Default: SOME_VARIABLE
    Description: Name of the parameter to export
  
  ParamValue:
    Type: String
    Default: some_value
    Description: Value of the parameter to export

Resources:

  SSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${TenantId}/${ParamName}"
      Type: String
      Value: !Ref ParamValue
      Tags:
        Name: !Sub "${TenantId}-${ParamName}"
        TenantId: !Ref TenantId

Outputs:
  ParameterName:
    Description: Name of the exported SSM parameter
    Value: !Ref SSMParameter
    Export:
      Name: !Sub "${TenantId}-${ParamName}"

  
