
Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used to prefix exported outputs.

  DomainName:
    Type: String
    Description: Custom domain name for the CloudFront distribution (e.g., www.example.com)
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-_.]*[a-zA-Z0-9]$

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain

Resources:
  # Route53 Record for custom domain
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${EnvId}-DistributionDomainName"
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  
  WebsiteURL:
    Description: Website URL with custom domain
    Value: !Sub "https://${DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"