# BUCKET_NAME="moontracer-distribution"
# DOMAIN_NAME="moontracer.faermanj.com"
# ZONE_ID="Z044981111XDI2RGQ2GM9"
# CERTIFICATE_ARN="arn:aws:acm:us-east-1:730335617563:certificate/777043cb-290c-4e63-8a20-c970da31a8bf"

# aws cloudformation deploy --template-file cloudformation/static-distribution/template.cform.yaml --stack-name "moontracer-stack" --parameter-overrides BucketName=$BUCKET_NAME DomainName=$DOMAIN_NAME HostedZoneId=$ZONE_ID CertificateArn=$CERTIFICATE_ARN --capabilities CAPABILITY_IAM

# aws s3 sync ./solutions/moontracer-workshop/distribution s3://$BUCKET_NAME --delete

Description: "Static website distribution with S3 bucket, CloudFront distribution, and Origin Access Control"

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used to prefix exported outputs.

  DomainName:
    Type: String
    Description: Custom domain name for the CloudFront distribution (e.g., www.example.com)
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-_.]*[a-zA-Z0-9]$

  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for HTTPS

Resources:
  # S3 Bucket for static files
  DistributionBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Origin Access Control for CloudFront to access S3
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: !Sub "Origin Access Control for ${AWS::StackName}"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: !Sub "Static distribution for ${DomainName}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          LambdaFunctionAssociations:
            - EventType: origin-response
              LambdaFunctionARN:
                Fn::ImportValue: !Sub "${EnvId}-EdgeCorsFunctionVersion"
        CacheBehaviors:
          - PathPattern: "/edge/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Headers:
                - Content-Type
              Cookies:
                Forward: none
            LambdaFunctionAssociations:
              - EventType: origin-request
                IncludeBody: true
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub "${EnvId}-EdgeFunctionVersion"
              - EventType: origin-response
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub "${EnvId}-EdgeCorsFunctionVersion"
          - PathPattern: "/fn/*"
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: false
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Content-Type
              Cookies:
                Forward: all
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketDomainName"
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: ApiOrigin
            DomainName: 
              Fn::ImportValue: 
                !Sub "${EnvId}-PresenceAPIHost"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  # Bucket Policy to allow CloudFront access via OAC
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: CloudFrontDistribution
    Properties:
      Bucket:
        Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketName"
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              Fn::Sub:
                - "arn:aws:s3:::${ResourcesBucketName}/*"
                - ResourcesBucketName:
                    Fn::ImportValue: !Sub "${EnvId}-ResourcesBucketName"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"



Outputs:
  BucketDomainName:
    Description: Regional domain name of the S3 bucket
    Value: !GetAtt DistributionBucket.RegionalDomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"

  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"

  DistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${EnvId}-DistributionDomainName"


  OriginAccessControlId:
    Description: Origin Access Control ID
    Value: !Ref OriginAccessControl
    Export:
      Name: !Sub "${AWS::StackName}-OACId"
