AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda@Edge root redirect for Presence

Parameters:
  EnvId:
    Type: String
    Default: project
    Description: Environment identifier used to prefix exported outputs.

Resources:
  EdgeRootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: presence_edge_root.app.handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 5
      AutoPublishAlias: live
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: 'sts:AssumeRole'

Outputs:
  EdgeRootFunctionVersion:
    Description: Lambda@Edge root redirect versioned ARN for CloudFront association
    Value: !Ref EdgeRootFunction.Version
    Export:
      Name: !Sub "${EnvId}-EdgeRootFunctionVersion"
  EdgeRootFunctionArn:
    Description: Lambda@Edge root redirect function ARN
    Value: !GetAtt EdgeRootFunction.Arn
    Export:
      Name: !Sub "${EnvId}-EdgeRootFunctionArn"
